version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: image-object-detection
    parameters:
      dockerfile:
        type: string
      tag:
        type: string

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Docker login
          command: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}

      - run:
          name: Build image
          command: docker build -f << parameters.dockerfile >> -t tkislan/hostpath-provisioner:<< parameters.tag >> .

      - run:
          name: Push image
          command: docker push tkislan/hostpath-provisioner:<< parameters.tag >>

workflows:
  version: 2
  build:
    jobs:
      - build:
          name: 'AMD64'
          dockerfile: Dockerfile
          tag: 'amd64-latest'
      - build:
          name: 'ARMv7'
          dockerfile: Dockerfile.armhf
          tag: 'armv7-latest'
      - build:
          name: 'ARM64'
          dockerfile: Dockerfile.armhf
          tag: 'arm64v8-latest'
