version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: image-object-detection
    parameters:
      goarch:
        type: string
      goarm:
        type: string
      img:
        type: string
      tag:
        type: string

    steps:
      - checkout

      - setup_remote_docker

      # - run:
      #     name: Docker login
      #     command: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}

      - run:
          name: Build image
          # command: docker build --build-arg MODEL_URL="<< parameters.model_url >>" -t ${IMAGE_NAME} .
          command: docker build --build-arg goarch="<< parameters.goarch >>" --build-arg goarm="<< parameters.goarm >>" --build-arg img="<< parameters.img >>" -t tkislan/hostpath-provisioner:"<< parameters.tag >>" .

      # - run:
      #     name: Push image
      #     command: docker push tkislan/hostpath-provisioner:"<< parameters.tag >>"

workflows:
  version: 2
  build:
    jobs:
      - build:
          name: 'AMD64'
          goarch: amd64
          goarm: ''
          img: 'alpine:3.11.3'
          tag: 'amd64-latest'
      - build:
          name: 'ARMv7'
          goarch: arm
          goarm: 7
          img: 'arm32v7/alpine:3.11.3'
          tag: 'armv7-latest'
